### ISSUE TITLE
Media Query

### ISSUE THREAD

**Issue by whitsats** [whitsats/myBlog#9]
# CSS3 媒体查询与响应式布局

## 第一章 序论

现今每天都有更多的手机和平板电脑问市。消费者能够拥有可想象到的各种规格和形状的设备，但是网站开发人员却面临一个挑战：如何使他们的网站在传统浏览器、手机和平板电脑浏览器上有很好的效果，如何在各种大小的屏幕上提供一流的用户体验？  
答案是：采用响应式设计。  
响应式设计可以随所显示的屏幕大小而改变。实现响应式设计的主要方法是使用 CSS 媒体查询。
Bootstrap的栅格系统就是通过媒体查询来实现的。

## 第二章 回顾媒体类型 media type

HTML4 和 CSS2支持根据媒体类型(media type)加载。
比如,如果是'屏幕设备'，则加载`screen.css`，如果是'打印设备'，则加载`print.css`。  

HTML4和CSS2 支持媒体类型来决定使用CSS样式,例:

```html
<link rel="stylesheet" type="text/css" media="screen" href="sans-serif.css">
<link rel="stylesheet" type="text/css" media="print" href="serif.css">
```
我们同样可以在CSS样式表中，声明条文适用于某些媒体类型。

```css
@media screen {
  * { font-family: sans-serif }
}
```

可以在使用@import导入CSS时使用媒体查询，有条件地向当前样式表中加载其他样式表。

```css
@import url("serif.css") screen;
```

`print`和`screen`媒体类型是HTML4中定义的.
HTML4定义的媒体类型如下:

+ **screen** 屏幕
+ **print** 打印机
+ **all** 所有
+ aural 声音
+ braille 盲文
+ handheld移动设备
+ projection 投影仪
+ tty 打字机
+ tv 电视
+ embossed 盲文打印

令人尴尬的是,除了前3种类型,剩下的几乎没人用,实际已经废弃了.

## 第三章 媒体查询 media query

媒体查询是评估 True 或 False 的一种表达。如果为 True，则继续使用样式表。如果为 False，则不能使用样式表。这种简单逻辑通过表达式变得更加强大，使我们能够更灵活地对特定的设计场景使用自定义的显示规则。  

媒体查询(media query)则根据媒体类型(medir type)和由媒体特征(media features)值组成的表达式.
媒体特征值如: `width` , `height`,`color`,即宽,高,色彩等.

共有13种特征(重点记住前3种) , 如下:

| 设 备 特 性 | 是否允许 min/max 前缀 | 特 性 的 值 | 说    明 |
| ------------- |:-------------:| -----:|:-----|
| width | 允许 | 含单位的数值 | 指定浏览器窗口的宽度大小， 如480像素 |
| height | 允许 | 含单位的数值 | 指定浏览器窗口的高度大小， 如320像素 |
| orientation | 不允许 | 字符串值 | 指定移动设备浏览器的窗口方向。 只能指定portrait（纵向）和landscape （横向）两个值 |
| device-width | 允许 | 含单位的数值 | 指定移动设备的屏幕分 辨率宽度大小，如480像素 |
| device-height | 允许 | 含单位的数值 | 指定移动设备的屏幕分 辨率高度大小，如320像素 |
| aspect-radio | 允许 | 比例值 | 指定移动设备浏览器窗口的 纵横比例，如16:9 |
| device-aspect-radio | 允许 | 比例值 | 指定移动设备屏幕分辨率的 纵横比例，如16:9 |
| color | 允许 | 整数值 | 指定移动设备使用多少位的颜色值 |
| color-index | 允许 | 整数值 | 指定色彩表的色彩数 |
| monochrome | 允许 | 整数值 | 指定单色帧缓冲器中每像素的字节数 |
| resolution | 允许 | 分辨率值 | 指定移动设备屏幕的分辨率 |
| scan | 不允许 | 字符串值 | 指定电视机类型设备的扫描方式。 只能指定两种值：progressive表 示逐行扫描和interlace表示隔行扫描 |
| grid | 不允许 | 整数值 | 指定设备是基于栅格还是基于位图。 基于栅格时该值为1，否则为0 |

## 第四章 媒体查询实战

```css
@media screen and (width: 600px){
    body {
        background: gray;
    }
}
```
上例指,对于屏幕且浏览器宽600px像素时,启用指定的css.
缩放浏览器试一下, 当浏览器窗口恰好是`600px`宽时,背景变灰.

上例中的媒体查询不是很实用,因为宽度恰好`400px`像素的条件太苛刻.
在实战中,用范围表达宽度更普遍.

```css
@media screen and (min-width: 600px){
    body {
        background: gray;
    }
}
```

上例指:对于屏幕且最小600宽(>=600px)的浏览器时,启用指定的css.
拖动浏览器试一下?

同时,打印预览再看一下背景色,想一想为什么?

```css
@media (orientation:portrait){
    body {
        background: gray;
    }
}

@media (orientation:landscape){
    body {
        background: blue;
    }
}
```
上例中,指屏幕`height>width`时,如手机竖直时,和屏幕`width>height`,如手机横放时,启动指定的css。
>在针对所有设备的媒体查询中，可以使用简写语法，即省略关键字all（以及紧随其后的and）。换句话说，如果不指定关键字，则关键字就是all。

## 第五章 复杂表达式

媒体查询表达式还可以更复杂。

#### 5.1 and联查

在表达式中，我们可以根据自己的喜好和需求使用任意数量的 and 条件。如果想要增加其他条件来检查特定的屏幕方向，只需添加另一个 and 关键词，后跟 orientation 媒体查询。

```css
@media screen and (min-width:768px) and (max-width:1200px) and (orientation:landscape){
  *{
    background:blue;
  }
}
```

#### 5.2 or条件

媒体查询中使用逗号分隔效果等同于 or 逻辑操作符。当使用逗号分隔的媒体查询时，如果任何一个媒体查询返回真，样式就是有效的。逗号分隔的列表中每个查询都是独立的，一个查询中的操作符并不影响其它的媒体查询。

```css
@media (width:768px), screen and (orientation:portrait) {
    * {
        background: blue;
    }
}
```

#### 5.3 not条件

not 关键字应用于整个媒体查询，在媒体查询为假时返回真，但仅能应用于整个查询，而不能单独应用于一个独立的查询。所有的not判断都在媒体查询的最后进行。

注意区分：

```css
@media not all and (min-width:768px) {
  *{
    background:blue;
  }
}
```

等价于：

```css
@media not (all and (min-width:768px)) {
  *{
    background:blue;
  }
}
```
>虽然这么写也是错误的，我们只是用来理解not的判断顺序。

而不是：

```css
@media (not all) and (min-width:768px){
  *{
    background:blue;
  }
}
```
